<a href="https://colab.research.google.com/github/4wsjad/DATA-MODELING-AND-VISUALIZATION/blob/main/LAB_EXP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
#1D array
a=np.array([1,2,3,4,5])
print("1D Array:\n",a)
#2D array
b=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",b)
#Array of zeros
c= np.zeros((3,3))
print("Zero:\n",c)
#array of ones
d= np.ones((2,4))
print("Ones:\n",d)
#range of numbers
e= np.arange(0,20,2)
print("Range:\n",e)
A=np.random.randint(1,100,(20,10))
np.mean(A,axis=1)
np.mean(A)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zero:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range:
 [ 0  2  4  6  8 10 12 14 16 18]


np.float64(53.685)